#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
echo 'Initializing calculator...' . PHP_EOL;
runInteractive();
function runInteractive(): void
{
    $cli = new \FintinaMadalin\CliCalculator\CalculatorService();
    while (true) {
        echo "Enter an operation (+, -, *, /, sqrt), or 'exit' to quit: ";
        $input = trim(fgets(STDIN));

        if ($input === 'exit') {
            break;
        }

        $tokens = explode(' ', $input);

        if (count($tokens) < 2) {
            echo "Invalid input. Please enter the operation in the format 'number1 operation number2'.\n";
            continue;
        }
        list($num1, $operation, $num2) = count($tokens) == 2 ? [...$tokens, null] : $tokens;

        try {
            $result = $cli->calculate($operation, (float)$num1, (float)$num2);
            echo "Result: $result\n";
        } catch (Exception $e) {
            echo 'Error: ' . $e->getMessage() . "\n";
        }
    }
}